---
# This workflow will validate the Packer AMI templates created using the Hashicorp Configuration Language (HCL2)
name: Packer AMI template validation

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate packer template for the custom AMI
    steps:
      - name: Checkout code from branch
        uses: actions/checkout@v3

      - name: Create packer variables
        run: |
          touch ami.pkrvars.hcl
          echo ami_prefix=\"${{ secrets.AMI_PREFIX }}\" >> ami.pkrvars.hcl
          echo OS=\"${{ secrets.OS }}\" >> ami.pkrvars.hcl
          echo ubuntu_version=\"${{ secrets.UBUNTU_VERSION }}\" >> ami.pkrvars.hcl
          echo ssh_username=\"${{ secrets.SSH_USERNAME }}\" >> ami.pkrvars.hcl
          echo subnet_id=\"${{ secrets.SUBNET_ID }}\" >> ami.pkrvars.hcl
          echo ami_users=\"${{ secrets.AMI_USERS }}\" >> ami.pkrvars.hcl
          echo source_ami=\"${{ secrets.SOURCE_AMI }}\" >> ami.pkrvars.hcl
          echo aws_region=\"${{ env.AWS_REGION }}\" >> ami.pkrvars.hcl
          echo instance_type=\"${{ secrets.INSTANCE_TYPE}}\" >> ami.pkrvars.hcl
          echo volume_size=\"${{ secrets.VOLUME_SIZE}}\" >> ami.pkrvars.hcl
          echo volume_type=\"${{ secrets.VOLUME_TYPE}}\" >> ami.pkrvars.hcl
          echo device_name=\"${{ secrets.DEVICE_NAME}}\" >> ami.pkrvars.hcl

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Packer format
        id: fmt
        run: "packer fmt ."

      - name: Packer init
        id: init
        run: "packer init ubuntu.ami.pkr.hcl"

      - name: Validate packer template
        id: validate
        run: "packer validate -evaluate-datasources \
          --var-file=ami.pkrvars.hcl ubuntu.ami.pkr.hcl"
